version: "3.8"

services:
  db-postgres:
    container_name: postgres
    restart: always
    user: postgres
    build:
      context: .
      dockerfile: ./imagem_base/Dockerfile.db-postgres
    environment:
      - POSTGRES_DB=eletro-tech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 128M
    networks:
      - eletro-tech-rede
  app-eletro-tech:
    container_name: eletro-tech
    restart: always
    image: fosales/eletrotech:0.0.2
    environment:
      - ELETRO_TECH_SPRING_DOCKER_COMPOSE_ENABLE=false
      - ELETRO_TECH_SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/eletro-tech
      - ELETRO_TECH_SPRING_DATASOURCE_USERNAME=postgres
      - ELETRO_TECH_SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - db-postgres
    networks:
      - eletro-tech-rede


volumes:
  postgres_data:
networks:
  eletro-tech-rede:
    driver: bridge
