spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-interface

  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false


logging:
  level:
    br:
      com:
        fsales: info