spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:eletrotech_dev
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-interface

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    br:
      com:
        fsales: debug