spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${ELETRO_TECH_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eletro-tech}
    username: ${ELETRO_TECH_SPRING_DATASOURCE_USERNAME:postgres}
    password: ${ELETRO_TECH_SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    validate-on-migrate: false
  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    br:
      com:
        fsales: debug
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG

