spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
  mvc:
    servlet:
      path: /api

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  jpa:
    show-sql: false
    open-in-view: true


server:
  error:
    include-stacktrace: never # desabilitar stacktrace no json que e retornado em caso de erro

application:
  title: ${spring.application.name}
  version: ${spring.application.version}
  api-pessoa:
    swagger:
      name: API de gestão de pessoas
      description: Tem como objetivo permitir o cadastro e gerenciamento de informações sobre as pessoas relacionadas aos usuários cadastrados em nosso sistema.


