CREATE TABLE PESSOA
(
    ID              UUID         NOT NULL,
    ID_PARENT       UUID,
    NOME            VARCHAR(100) NOT NULL,
    SOBRENOME       VARCHAR(100) NOT NULL,
    CPF             VARCHAR(11)  NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    SEXO            VARCHAR(1)   NOT NULL,
    PARENTESCO      VARCHAR(1),
    CREATED         TIMESTAMP(6) WITH TIME ZONE,
    UPDATED         TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE PESSOA
    ADD CONSTRAINT PK_PESSOA PRIMARY KEY (ID);

ALTER TABLE IF EXISTS PESSOA
    ADD CONSTRAINT FK_PARENT_PESSOA FOREIGN KEY (ID_PARENT) REFERENCES PESSOA;