CREATE TABLE ELETRODOMESTICO
(
    ID               UUID         NOT NULL,
    NOME             VARCHAR(255) NOT NULL,
    MODELO           VARCHAR(255) NOT NULL,
    FABRICANTE       VARCHAR(255) NOT NULL,
    POTENCIA         INTEGER      NOT NULL,
    VOLTAGEM         INTEGER      NOT NULL,
    TEMPO_USO_DIARIO INTEGER      NOT NULL,
    CREATED          TIMESTAMP(6) WITH TIME ZONE,
    UPDATED          TIMESTAMP(6) WITH TIME ZONE
);


ALTER TABLE ELETRODOMESTICO
    ADD CONSTRAINT PK_ELETRODOMESTICO PRIMARY KEY (ID);