CREATE TABLE ENDERECO
(
    ID          UUID         NOT NULL,
    RUA         VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    NUMERO      INTEGER      NOT NULL,
    BAIRRO      VARCHAR(100) NOT NULL,
    CIDADE      VARCHAR(100) NOT NULL,
    ESTADO      VARCHAR(2)   NOT NULL,
    CREATED     TIMESTAMP(6) WITH TIME ZONE,
    UPDATED     TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE ENDERECO
    ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (ID);

