-- ADICINAR NOVAS COLUNAS
ALTER TABLE ENDERECO
    ADD ID_PESSOA UUID NOT NULL;
ALTER TABLE ENDERECO
    ADD CEP VARCHAR(8) NOT NULL;
ALTER TABLE ENDERECO
    ADD NOME_ENDERECO VARCHAR(255) NOT NULL;

-- ADINCIONAR CONSTRAINTS
ALTER TABLE IF EXISTS ENDERECO
    ADD CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID);

-- DELETAR PRIMARY KEY
ALTER TABLE IF EXISTS ENDERECO
    DROP CONSTRAINT PK_ENDERECO;

-- ADICIONAR NOVA PRIMARY KEY
ALTER TABLE IF EXISTS ENDERECO
    ADD CONSTRAINT PK_ENDERECO_PESSOA PRIMARY KEY (ID, ID_PESSOA);


