-- ADICINAR NOVAS COLUNAS
ALTER TABLE ELETRODOMESTICO
    ADD ID_PESSOA UUID NOT NULL;

ALTER TABLE ELETRODOMESTICO
    ADD ID_ENDERECO UUID NOT NULL;

-- ADINCIONAR CONSTRAINTS
-- ALTER TABLE IF EXISTS ELETRODOMESTICO
--     ADD CONSTRAINT FK_ELETRODOMENTICO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID);
--
-- ALTER TABLE IF EXISTS ELETRODOMESTICO
--     ADD CONSTRAINT FK_ELETRODOMENTICO_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID);