-- ADICINAR NOVAS COLUNAS
ALTER TABLE ELETRODOMESTICO
    ADD ID_PESSOA UUID NOT NULL;

ALTER TABLE ELETRODOMESTICO
    ADD ID_ENDERECO UUID NOT NULL;

-- CREATE CONSTRAINT
ALTER TABLE IF EXISTS ELETRODOMESTICO
    ADD CONSTRAINT FK_ELETRODOMENTICO_ENDERECO_PESSOA FOREIGN KEY (ID_ENDERECO, ID_PESSOA) REFERENCES ENDERECO (ID, ID_PESSOA);